[relay]

  [relay.1]
  module = 8.0
  relay = 1.0

  [relay.2]
  module = 2.0
  relay = 1.0

  [relay.3]
  module = 5.0
  relay = 1.0

  [relay.4]
  module = 8.0
  relay = 2.0

  [relay.5]
  module = 2.0
  relay = 2.0

  [relay.6]
  module = 5.0
  relay = 2.0

  [relay.7]
  module = 8.0
  relay = 3.0

  [relay.8]
  module = 2.0
  relay = 3.0

  [relay.9]
  module = 5.0
  relay = 3.0

  [relay.10]
  module = 8.0
  relay = 4.0

  [relay.11]
  module = 2.0
  relay = 4.0

  [relay.12]
  module = 5.0
  relay = 4.0

  [relay.13]
  module = 9.0
  relay = 1.0

  [relay.14]
  module = 3.0
  relay = 1.0

  [relay.15]
  module = 6.0
  relay = 1.0

  [relay.16]
  module = 9.0
  relay = 2.0

  [relay.17]
  module = 3.0
  relay = 2.0

  [relay.18]
  module = 6.0
  relay = 2.0

  [relay.19]
  module = 9.0
  relay = 3.0

  [relay.20]
  module = 3.0
  relay = 3.0

  [relay.21]
  module = 6.0
  relay = 3.0

  [relay.22]
  module = 9.0
  relay = 4.0

  [relay.23]
  module = 3.0
  relay = 4.0

  [relay.24]
  module = 6.0
  relay = 4.0

  [relay.25]
  module = 10.0
  relay = 1.0

  [relay.26]
  module = 4.0
  relay = 1.0

  [relay.27]
  module = 7.0
  relay = 1.0

  [relay.28]
  module = 10.0
  relay = 2.0

  [relay.29]
  module = 4.0
  relay = 2.0

  [relay.30]
  module = 7.0
  relay = 2.0

  [relay.31]
  module = 10.0
  relay = 3.0

  [relay.32]
  module = 4.0
  relay = 3.0

  [relay.33]
  module = 7.0
  relay = 3.0

  [relay.34]
  module = 10.0
  relay = 4.0

  [relay.35]
  module = 4.0
  relay = 4.0

  [relay.36]
  module = 7.0
  relay = 4.0
