[relay]

  [relay.1]
  module = 8
  relay = 1

  [relay.2]
  module = 2
  relay = 1

  [relay.3]
  module = 5
  relay = 1

  [relay.4]
  module = 8
  relay = 2

  [relay.5]
  module = 2
  relay = 2

  [relay.6]
  module = 5
  relay = 2

  [relay.7]
  module = 8
  relay = 3

  [relay.8]
  module = 2
  relay = 3

  [relay.9]
  module = 5
  relay = 3

  [relay.10]
  module = 8
  relay = 4

  [relay.11]
  module = 2
  relay = 4

  [relay.12]
  module = 5
  relay = 4

  [relay.13]
  module = 9
  relay = 1

  [relay.14]
  module = 3
  relay = 1

  [relay.15]
  module = 6
  relay = 1

  [relay.16]
  module = 9
  relay = 2

  [relay.17]
  module = 3
  relay = 2

  [relay.18]
  module = 6
  relay = 2

  [relay.19]
  module = 9
  relay = 3

  [relay.20]
  module = 3
  relay = 3

  [relay.21]
  module = 6
  relay = 3

  [relay.22]
  module = 9
  relay = 4

  [relay.23]
  module = 3
  relay = 4

  [relay.24]
  module = 6
  relay = 4

  [relay.25]
  module = 10
  relay = 1

  [relay.26]
  module = 4
  relay = 1

  [relay.27]
  module = 7
  relay = 1

  [relay.28]
  module = 10
  relay = 2

  [relay.29]
  module = 4
  relay = 2

  [relay.30]
  module = 7
  relay = 2

  [relay.31]
  module = 10
  relay = 3

  [relay.32]
  module = 4
  relay = 3

  [relay.33]
  module = 7
  relay = 3

  [relay.34]
  module = 10
  relay = 4

  [relay.35]
  module = 4
  relay = 4

  [relay.36]
  module = 7
  relay = 4
